# Generated by Django 3.2.3 on 2021-05-28 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('adminUserPassword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'adminUser',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('majorName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('faculty', models.CharField(choices=[('CHS', 'College of Humanities and Sciences'), ('BIZ', 'Business & Accountancy'), ('COM', 'Computing'), ('DEN', 'Dentistry'), ('DE', 'Design & Environment'), ('ENGR', 'Engineering'), ('LAW', 'Law'), ('MED', 'Medicine'), ('NSG', 'Nursing'), ('PHAR', 'Pharmacy'), ('MUS', 'Music')], max_length=50)),
            ],
            options={
                'verbose_name': 'Major',
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='MemberUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('userID', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=30)),
                ('userNUSEmail', models.EmailField(max_length=254)),
                ('displayName', models.CharField(max_length=30)),
                ('faculty', models.CharField(choices=[('CHS', 'College of Humanities and Sciences'), ('BIZ', 'Business & Accountancy'), ('COM', 'Computing'), ('DEN', 'Dentistry'), ('DE', 'Design & Environment'), ('ENGR', 'Engineering'), ('LAW', 'Law'), ('MED', 'Medicine'), ('NSG', 'Nursing'), ('PHAR', 'Pharmacy'), ('MUS', 'Music')], max_length=50)),
                ('yearOfStudy', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], max_length=6)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.major')),
            ],
            options={
                'verbose_name': 'Member User',
                'verbose_name_plural': 'Member Users',
                'db_table': 'memberUser',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Acad', 'Academic'), ('Non-Acad', 'Non-Academic')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('textContent', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Upvote', 'Upvote'), ('Downvote', 'Downvote'), ('None', 'None')], default='None', max_length=20)),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='server.post')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='server.memberuser')),
            ],
            options={
                'verbose_name': 'Vote',
                'db_table': 'vote',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tagID',
            field=models.ForeignKey(db_column='tag', on_delete=django.db.models.deletion.RESTRICT, to='server.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='userID',
            field=models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.memberuser'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('textContent', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='server.post')),
                ('userID', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.memberuser')),
            ],
            options={
                'verbose_name': 'Comment',
                'db_table': 'comment',
            },
        ),
    ]
