# Generated by Django 3.2.3 on 2021-06-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyID', models.AutoField(primary_key=True, serialize=False)),
                ('textContent', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('commentID', models.ForeignKey(db_column='commentID', on_delete=django.db.models.deletion.CASCADE, to='server.comment')),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='server.post')),
                ('userID', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.memberuser')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'db_table': 'reply',
            },
        ),
    ]
