# Generated by Django 3.2.3 on 2021-05-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberuser',
            old_name='displayName',
            new_name='username',
        ),
    ]
