# Generated by Django 3.2.3 on 2021-05-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_displayname_memberuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberuser',
            name='userID',
        ),
    ]
