# Generated by Django 3.2.3 on 2021-05-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_memberuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberuser',
            name='faculty',
            field=models.CharField(blank=True, choices=[('CHS', 'College of Humanities and Sciences'), ('BIZ', 'Business & Accountancy'), ('COM', 'Computing'), ('DEN', 'Dentistry'), ('DE', 'Design & Environment'), ('ENGR', 'Engineering'), ('LAW', 'Law'), ('MED', 'Medicine'), ('NSG', 'Nursing'), ('PHAR', 'Pharmacy'), ('MUS', 'Music')], max_length=50),
        ),
        migrations.AlterField(
            model_name='memberuser',
            name='major',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='server.major'),
        ),
        migrations.AlterField(
            model_name='memberuser',
            name='yearOfStudy',
            field=models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], max_length=6),
        ),
    ]
