# Generated by Django 3.2.3 on 2021-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_post_moduleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replyCount',
            field=models.IntegerField(default=0),
        ),
    ]
