# Generated by Django 3.2.3 on 2021-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_event_enddatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default='2017-05-24T10:30'),
            preserve_default=False,
        ),
    ]
