# Generated by Django 3.2.3 on 2021-05-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210531_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberuser',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.major'),
        ),
    ]
