# Generated by Django 3.2.3 on 2021-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_memberuser_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberuser',
            name='userPassword',
            field=models.CharField(max_length=100),
        ),
    ]
