# Generated by Django 3.2.3 on 2021-07-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDateTime',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDateTime',
            new_name='start',
        ),
    ]
