# Generated by Django 3.2.3 on 2021-06-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20210627_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userID',
            field=models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.memberuser'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='userID',
            field=models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.memberuser'),
        ),
    ]
